name: Create development builds APK

on:
  push:
    branches: ["apk"]

jobs:
  android_development_build:
    name: Build Android
    type: build
    params:
      platform: android
      profile: preview
