#  Preview APK build workflow for EAS Build
#  This workflow is triggered on APK itself.
name: Publish preview update

on:
  push:
    branches: ["host"]

jobs:
  publish_preview_update:
    name: Publish preview update
    type: update
    params:
      branch: ${{ github.ref_name || 'test' }}
