name: Publish update

on:
  push:
    branches: ["dev", "host"]

jobs:
  update:
    name: Update
    type: update
    params:
      branch: ${{ github.ref_name || 'test'}}
      message: ${{ github.event.head_commit.message }}

  deploy:
  name: Deploy
  type: deploy
  params:
    branch: ${{ github.ref_name || 'test'}}
    message: ${{ github.event.head_commit.message }}
    prod: true
